version: '3'

services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    command: postgres -c listen_addresses='*'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/tmp
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./env

  web:
    build: .
    command: python manage.py runserver 0:8000
    restart: always
    container_name: web
    working_dir: /code/
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./env

volumes:
  postgres_data:

networks:
  judge: {}
