version: '3'

services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    command: postgres -c listen_addresses='*'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./env

  service:
    build: .
    command: python manage.py runserver 0:6001
    restart: always
    container_name: service
    working_dir: /code/
    volumes:
      - .:/code
    ports:
      - 6001:6001
    depends_on:
      - postgres
    env_file:
      - ./env

  web:
    build: ./judge_web
    command: ["npm", "start"]
    volumes:
      - ./judge_web/:/code
    depends_on:
      - service
    ports:
      - "3000:3000"
volumes:
  postgres_data:

networks:
  judge: {}
