# Generated by Django 3.1.2 on 2020-10-23 18:11

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profiles',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
