# Generated by Django 3.1.2 on 2020-10-25 12:59

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    UserType = apps.get_model("accounts", "UserType")
    data = [UserType(type='Student'), UserType(type='Admin')]
    UserType.objects.bulk_create(data)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
