# Generated by Django 3.1.2 on 2020-10-23 18:44

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201023_1811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profiles',
            managers=[
                ('objects', accounts.models.ProfileManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usertype'),
        ),
    ]
